name: Threadfin Build
on:
  push:
    branches:
      - main
    tags: "v*"
permissions:
  contents: write
jobs:
  push:
    name: Push to Docker
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build Setup
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64

      - name: Docker Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          no-cache: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_URL }}/daftfuzz/threadfin:dev

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "latest"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: dist/*