name: Threadfin Build
on:
  push:
    branches:
      - main
    tags: "v*"
permissions:
  contents: write
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up and Build
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
        id: go
      - name: Build Binaries
        run: |
         go mod tidy && go mod vendor
         echo "Building Linux"
         env GOOS=linux GOARCH=amd64 go build -o dist/Threadfin_linux_amd64

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: dist/*

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build Setup
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64

      - name: Docker Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          no-cache: true
          platforms: linux/amd64
          tags: daftfuzz/threadfin:dev